apiVersion: v1
kind: ConfigMap
metadata:
  name: remediation-module-config
data:
  config.yaml: |
    log:
      level: "info"
    server:
      port: 8080
      shutdownTimeout: 15
    smtp:
      # --- Changed: 네이버 SMTP 정보로 변경 ---
      host: "smtp.naver.com"
      port: 465 # SSL을 사용하도록 포트 변경경
      username: "judemin2087"
      fromEmail: "judemin2087@naver.com"
      toEmail: "judemin2087@naver.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
type: Opaque
data:
  password: WlhoaGJYQmxZUT09
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediation-module-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remediation-deploy-patcher
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
#  Cordon/Drain을 위한 권한 추가
- apiGroups: [""] # "core" API 그룹
  resources: ["nodes"]
  verbs: ["get", "list", "patch"] # Cordon(patch) 및 노드 상태 확인(get, list)
- apiGroups: [""] # "core" API 그룹
  resources: ["pods"]
  verbs: ["get", "list"] # Drain을 위해 노드의 Pod 목록 조회
- apiGroups: ["policy", ""] # "policy" 또는 "core" API 그룹
  resources: ["pods/eviction"]
  verbs: ["create"] # Drain(Eviction API) 실행
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remediation-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: remediation-deploy-patcher
subjects:
- kind: ServiceAccount
  name: remediation-module-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remediation-module
  template:
    metadata:
      labels:
        app: remediation-module
    spec:
      serviceAccountName: remediation-module-sa
      containers:
      - name: remediation-module
        image: judemin/opslinked-ai-remediation
        ports:
        - containerPort: 8080
        env:
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-credentials
              key: password
        volumeMounts:
        - name: config-volume
          # /app/config.yaml 에서 /config.yaml 로 수정
          mountPath: /config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: remediation-module-config
---
apiVersion: v1
kind: Service
metadata:
  name: remediation-module-svc
spec:
  type: NodePort
  selector:
    app: remediation-module
  ports:
  - protocol: TCP
    port: 80 # 서비스가 노출할 포트
    targetPort: 8080 # Pod의 컨테이너 포트
    nodePort: 32563